name: aishell

on:
  push:
    branches:
      - download
  workflow_dispatch:

jobs:
  aishell:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download model
        shell: bash
        run: |
          mkdir aishell
          cd aishell

          wget -qq https://www.openslr.org/resources/33/data_aishell.tgz
          wget -qq https://www.openslr.org/resources/33/resource_aishell.tgz
          ls -lh

      - uses: actions/upload-artifact@v3
        with:
          name: aishell
          path: aishell
