name: csukuangfj-sherpa-onnx-zipformer-ctc-en-2023-10-02

on:
  push:
    branches:
      - download
  workflow_dispatch:

jobs:
  onnx-csukuangfj-sherpa-onnx-zipformer-ctc-en-2023-10-02:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download model
        shell: bash
        run: |
          git lfs install
          git clone https://huggingface.co/csukuangfj/sherpa-onnx-zipformer-ctc-en-2023-10-02
          rm -rf sherpa-onnx-zipformer-ctc-en-2023-10-02/.git

          sudo apt-get install -y tree

          tree ./sherpa-onnx-zipformer-ctc-en-2023-10-02
          ls -lh ./sherpa-onnx-zipformer-ctc-en-2023-10-02

      - uses: actions/upload-artifact@v2
        with:
          name: sherpa-onnx-zipformer-ctc-en-2023-10-02
          path: sherpa-onnx-zipformer-ctc-en-2023-10-02
