name: csukuangfj-sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20-bilingual

on:
  push:
    branches:
      - download
  workflow_dispatch:

jobs:
  csukuangfj--streaming-zipformer-bilingual-zh-en-2023-02-20-bilingual:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download model
        shell: bash
        run: |
          git lfs install
          git clone https://huggingface.co/csukuangfj/sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20
          rm -rf sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20/.git

          sudo apt-get install -y tree

          tree ./sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20
          ls -lh ./sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20

      - uses: actions/upload-artifact@v3
        with:
          name: sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20
          path: sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20
