name: csukuangfj-sherpa-onnx-streaming-zipformer-en-2023-06-26

on:
  push:
    branches:
      - download
  workflow_dispatch:

jobs:
  onnx-csukuangfj-sherpa-onnx-streaming-zipformer-en-2023-06-26:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install sherpa-onnx
        shell: bash
        run: |
          pip install sherpa-onnx

      - name: Download model
        shell: bash
        run: |
          git lfs install
          git clone https://huggingface.co/csukuangfj/sherpa-onnx-streaming-zipformer-en-2023-06-26
          rm -rf sherpa-onnx-streaming-zipformer-en-2023-06-26/.git

          sherpa-onnx \
            --tokens=./sherpa-onnx-streaming-zipformer-en-2023-06-26/tokens.txt \
            --encoder=./sherpa-onnx-streaming-zipformer-en-2023-06-26/encoder-epoch-99-avg-1-chunk-16-left-64.onnx \
            --decoder=./sherpa-onnx-streaming-zipformer-en-2023-06-26/decoder-epoch-99-avg-1-chunk-16-left-64.onnx \
            --joiner=./sherpa-onnx-streaming-zipformer-en-2023-06-26/joiner-epoch-99-avg-1-chunk-16-left-64.onnx \
            ./sherpa-onnx-streaming-zipformer-en-2023-06-26/test_wavs/0.wav

          sudo apt-get install -y tree

          tree ./sherpa-onnx-streaming-zipformer-en-2023-06-26
          ls -lh ./sherpa-onnx-streaming-zipformer-en-2023-06-26

      - uses: actions/upload-artifact@v3
        with:
          name: sherpa-onnx-streaming-zipformer-en-2023-06-26
          path: sherpa-onnx-streaming-zipformer-en-2023-06-26
