name: shaojieli-sherpa-onnx-streaming-zipformer-fr-2023-04-14-french

on:
  push:
    branches:
      - download
  workflow_dispatch:

jobs:
  onnx-streaming-zipformer-fr-2023-04-14-french:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download model
        shell: bash
        run: |
          git lfs install
          git clone https://huggingface.co/shaojieli/sherpa-onnx-streaming-zipformer-fr-2023-04-14
          rm -rf sherpa-onnx-streaming-zipformer-fr-2023-04-14

          sudo apt-get install -y tree

          tree ./sherpa-onnx-streaming-zipformer-fr-2023-04-14
          ls -lh ./sherpa-onnx-streaming-zipformer-fr-2023-04-14

      - uses: actions/upload-artifact@v2
        with:
          name: sherpa-onnx-streaming-zipformer-fr-2023-04-14.zip
          path: sherpa-onnx-streaming-zipformer-fr-2023-04-14
