name: vits-zh-aishell3

on:
  push:
    branches:
      - download
  workflow_dispatch:

jobs:
  vits-zh-aishell3:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Convert model
        shell: bash
        run: |
          cd .github/scripts
          ./vits-zh-aishell3.sh

      - name: Download model
        shell: bash
        run: |
          git lfs install
          git clone https://huggingface.co/csukuangfj/vits-zh-aishell3
          rm -rf vits-zh-aishell3/.git
          rm -v vits-zh-aishell3/*.pth

          sudo apt-get install -y tree
          tree ./vits-zh-aishell3
          ls -lh ./vits-zh-aishell3

      - uses: actions/upload-artifact@v3
        with:
          name: vits-zh-aishell3
          path: vits-zh-aishell3
