name: vits-piper-en_US

on:
  push:
    branches:
      - vits-piper-en-us
  workflow_dispatch:

jobs:
  vits-piper-en_US:
    runs-on: ubuntu-latest
    name: English US ${{ matrix.name }} ${{ matrix.type }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: amy
            type: [low, medium]
          - name: arctic
            type: low
          - name: danny
            type: low
          - name: hfc_male
            type: medium
          - name: joe
            type: medium
          - name: kathleen
            type: medium
          - name: kusal
            type: medium
          - name: l2arctic
            type: medium
          - name: lessac
            type: [low, medium, high]
          - name: libritts
            type: high
          - name: libritts_r
            type: medium
          - name: ryan
            type: [low, medium, high]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate model
        shell: bash
        run: |
          cd .github/scripts
          export NAME=${{ matrix.name }}
          export TYPE=${{ matrix.type }}
          ./vits-piper-en_US.sh

      - name: upload model to huggingface
        shell: bash
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          NAME: ${{ matrix.name }}
          TYPE: ${{ matrix.type }}
        run: |
          cd .github/scripts
          ls -lh
          git clone https://huggingface.co/csukuangfj/vits-piper-en_US-$NAME-$TYPE
          cd vits-piper-en_US-$NAME-$TYPE
          cp ../*onnx* .
          cp ../CMU-in-IPA.zip .
          cp ../lexicon.txt .
          cp ../tokens.txt .
          cp ../MODEL_CARD .

          git lfs track "lexicon.txt"

          git config --global user.email "csukuangfj@gmail.com"
          git config --global user.name "Fangjun Kuang"

          git status
          git add .
          git commit -m "update"
          git push https://csukuangfj:$HF_TOKEN@huggingface.co/csukuangfj/vits-piper-en_US-$NAME-$TYPE main

          cd ..
          rm -rf vits-piper-en_US-$NAME-$TYPE/.git
          mv vits-piper-en_US-$NAME-$TYPE ../..
          cd ../..
          sudo apt-get install -y tree
          tree ./vits-piper-en_US-$NAME-$TYPE
          ls -lh ./vits-piper-en_US-$NAME-$TYPE

      - uses: actions/upload-artifact@v3
        with:
          name: vits-piper-en_US-${{ matrix.name }}-${{ matrix.type }}
          path: vits-piper-en_US-${{ matrix.name }}-${{ matrix.type }}
