name: vits-piper-en_US-lessac-medium

on:
  push:
    branches:
      - download
  workflow_dispatch:

jobs:
  vits-piper-en_US-lessac-medium:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download model
        shell: bash
        run: |
          git lfs install
          git clone https://huggingface.co/csukuangfj/vits-piper-en_US-lessac-medium
          rm -rf vits-piper-en_US-lessac-medium/.git

          sudo apt-get install -y tree
          tree ./vits-piper-en_US-lessac-medium
          ls -lh ./vits-piper-en_US-lessac-medium

      - uses: actions/upload-artifact@v3
        with:
          name: vits-piper-en_US-lessac-medium
          path: vits-piper-en_US-lessac-medium
