name: vits-ljs

on:
  push:
    branches:
      - download
  workflow_dispatch:

jobs:
  vits-ljs:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download model
        shell: bash
        run: |
          git lfs install
          git clone https://huggingface.co/csukuangfj/vits-ljs
          rm -rf vits-ljs/.git
          rm -v vits-ljs/*.pth

          sudo apt-get install -y tree
          tree ./vits-ljs
          ls -lh ./vits-ljs

      - uses: actions/upload-artifact@v3
        with:
          name: vits-ljs
          path: vits-ljs
