name: vits-vctk

on:
  push:
    branches:
      - download
  workflow_dispatch:

jobs:
  vits-vctk:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download model
        shell: bash
        run: |
          git lfs install
          git clone https://huggingface.co/csukuangfj/vits-vctk
          rm -rf vits-vctk/.git

          sudo apt-get install -y tree
          tree ./vits-vctk
          ls -lh ./vits-vctk

      - uses: actions/upload-artifact@v3
        with:
          name: vits-vctk
          path: vits-vctk
