name: zengwei-icefall-asr-librispeech-zipformer-transducer-ctc-2023-06-13

on:
  push:
    branches:
      - download
  workflow_dispatch:

jobs:
  zengwei-icefall-asr-librispeech-zipformer-transducer-ctc-2023-06-13:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download model
        shell: bash
        run: |
          git lfs install
          git clone https://huggingface.co/Zengwei/icefall-asr-librispeech-zipformer-transducer-ctc-2023-06-13
          rm -rf icefall-asr-librispeech-zipformer-transducer-ctc-2023-06-13/.git
          rm -v icefall-asr-librispeech-zipformer-transducer-ctc-2023-06-13/exp/epoch-40.pt
          rm -rfv icefall-asr-librispeech-zipformer-transducer-ctc-2023-06-13/data/lm
          rm -v icefall-asr-librispeech-zipformer-transducer-ctc-2023-06-13/data/lang_bpe_500/*.pt

          sudo apt-get install -y tree

          tree ./icefall-asr-librispeech-zipformer-transducer-ctc-2023-06-13
          ls -lh ./icefall-asr-librispeech-zipformer-transducer-ctc-2023-06-13

      - uses: actions/upload-artifact@v3
        with:
          name: icefall-asr-librispeech-zipformer-transducer-ctc-2023-06-13
          path: icefall-asr-librispeech-zipformer-transducer-ctc-2023-06-13
